project_id = "xumnfngrhcxfhnemrozu"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.suggest-materials]
verify_jwt = false

[functions.generate-contract]
verify_jwt = false
